name: Chunye Yang
email: chunye@umich.edu

sections:
  Reading Notes:
    Etale Cohomology:
      description: Still updating, mosting following Lei Fu's book on etale cohomology. More detials of proof provided and some remarks and insights added.
      files:
        - title: Preliminaries on field theory
          description: 
  
        - title: Descent theory
          description: 
        - title: Etale and smooth morphisms
          description: 
        - title: Etale covering spaces
          description:
        - title: Group cohomology and Galois cohomology
          description: 

    FOAG Rising Sea: 
      description: Still updating, notes following Vakil's FOAG, mainly doing all the exercises and provide some of my own insight. A little bit messy in the beginning as topics are mixed together but the later parts are more clear and alligns with the sections on FOAG.
      files:
        - title: Proj separatedness and properness
        - title: Fibered product
        - title: Quasi-coherent sheaves
        - title: Dimension
        - title: Regularity and smoothness
        - title: Line bundles maps to projective spaces and divisors
        - title: Maps to projective spaces and properties of line bundles
        - title: Projective morphisms
        - title: Cech cohomology of quasicoherent sheaves
        - title: More on Cech cohomology of quasicoherent sheaves
        - title: Curves
        - title: Numerical intersection theory
        - title: Blow-up
        - title: Sheaf of differentials
        - title: Miscellaneous


    Fourier Mukai Transforms: 
      description: Still updating, notes took during Summer 2025 Umich REU project on derived categroies and Fourier–Mukai Transforms. Following Huybrechts's book on Fourier-Mukai transforms in algebraic geometry.
      files:
        - title: Triangulated categories
        - title: Derived categroies
        - title: Derived categories on coherent sheaves
        - title: Derived category and canonical bundle part 1
        - title: Fourier–Mukai transforms

    Intro to Homological Algebra: Intro to Homological Algebra

  Research & Publications:
    Representation stability in the (co)homology of vertical configuration spaces: https://arxiv.org/abs/2412.01128
