name: Chunye Yang
email: chunye@umich.edu

sections:
  Reading Notes:
    Etale Cohomology:
      description: 111
      files:
        - title: Descent theory
          description: 222
        - title: Etale and smooth morphisms
          description: 333
        - title: Etale covering spaces

    Intro to Homological Algebra: Intro to Homological Algebra

    Rising Sea Notes and Exercises: Blow-up

  Research & Publications:
    Representation stability in the (co)homology of vertical configuration spaces: https://arxiv.org/abs/2212.13227
